### ISSUE TITLE
Add Event

### ISSUE THREAD

**Issue by GromHoll** [KuzminMaxim/Project#3]
## Links
**Blocked By:** #12, #7, #8

## Flow
1. A person sees a map in front of him. 
2. Position on user detected by geotag
3. A person clicks on a specific location on this map. 
4. A window pops up that says: _"Write the subject of the event"_, _"Write the time of the event"_, and there are two buttons: _"Create"_ and _"Cancel"_. 
5. When you click on the _"Create"_ button, validation is run. If validation successfully completed an event is created and the person go to home page. When you click on the _"Cancel"_ button, the person returns back to the map.

### Event
Field | Type of data | Validation
------|---------------|------------
Coordinates | ? | Not empty
Time | Date | >= date of creation. Not empty
Name | Text | char limit? Not empty

**Comment by KuzminMaxim** [comment]
https://github.com/KuzminMaxim/Project/issues/7
https://github.com/KuzminMaxim/Project/issues/8

**Comment by KuzminMaxim** [comment]
https://github.com/KuzminMaxim/Project/issues/12
